### ISSUE TITLE
image links expire on website

### ISSUE THREAD

**Issue by mushon** [akariv/isvis-static#8]
See: https://v5.airtableusercontent.com/v1/15/15/1681041600000/M0EGWE_48ISUdfG9ycWUQA/BIeTfpAIUYprssAuGn61ED6bcnhclcGFOZVqaianl8Oljiz26l1TMlvGY95uHPov70vyULmVNDs_zOZFic7PEA/7kKiFzroQl3c80dmgLiqWFsW1dj_loau9clUTerHaFw

(the speaker profile images seem not to play nice…)

**Comment by akariv** [comment]
<img width="380" alt="Screen Shot 2023-04-10 at 16 45 05" src="https://user-images.githubusercontent.com/265333/230913291-4341a2ea-db4a-4f1a-8e92-4931330edce7.png">

Since these are small images, I might find a workaround.

**Comment by mushon** [comment]
תודה!!!
